=== nzzdev/Q-table/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Tabelle",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string",
      "Q:options": {
        "placeholder": "Der Titel bringt die Kernaussage der Tabelle auf den Punkt&#46;"
      }
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string"
    },
    "data": {
      "title": "Daten",
      "type": "object",
      "Q:type": "table",
      "Q:options": {
        "allowTranspose": false,
        "metaDataEditor": {
          "dataPropertyName": "table",
          "features": {
            "cells": {
              "propertyPath": "metaData.cells"
            }
          }
        }
      },
      "properties": {
        "table": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            }
          },
          "minItems": 1
        },
        "metaData": {
          "type": "object",
          "Q:options": {
            "compact": true
          },
          "properties": {
            "cells": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "rowIndex": {
                    "type": "number",
                    "Q:options": {
                      "hideInEditor": true
                    }
                  },
                  "colIndex": {
                    "type": "number",
                    "Q:options": {
                      "hideInEditor": true
                    }
                  },
                  "data": {
                    "type": "object",
                    "properties": {
                      "footnote": {
                        "title": "Fussnote",
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "sources": {
      "title": "Quelle(n)",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Quelle",
        "properties": {
          "text": {
            "title": "Quelle",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "Q:options": {
              "placeholder": "Direktlink zur Quelle, http://..."
            },
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }
            }
          }
        },
        "required": [
          "text"
        ]
      }
    },
    "notes": {
      "title": "Anmerkungen",
      "type": "string"
    },
    "options": {
      "title": "Optionen",
      "type": "object",
      "properties": {
        "hideTableHeader": {
          "title": "Spaltenüberschriften ausblenden",
          "type": "boolean",
          "default": false
        },
        "showTableSearch": {
          "title": "Tabellensuche anzeigen",
          "type": "boolean",
          "default": false,
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/showTableSearch",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          }
        },
        "cardLayout": {
          "title": "Card-Layout",
          "type": "boolean",
          "default": false
        },
        "cardLayoutIfSmall": {
          "title": "Card-Layout für Mobile",
          "type": "boolean",
          "default": false,
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/cardLayoutIfSmall",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          }
        },
        "minibar": {
          "title": "Minibars",
          "type": "object",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/minibars",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          },
          "properties": {
            "selectedColumn": {
              "title": "Spalte auswählen",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/selectedColumn",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/selectedColumnMinibar",
                    "fields": [
                      "options",
                      "data"
                    ]
                  }
                }
              }
            },
            "invertColors": {
              "title": "Farben invertieren",
              "type": "boolean",
              "default": false,
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/invertColors",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ]
              }
            },
            "barColor": {
              "title": "Farben manuell festlegen",
              "type": "object",
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "UserHasRole",
                    "config": {
                      "role": "expert-table"
                    }
                  },
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/barColor",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ]
              },
              "properties": {
                "positive": {
                  "title": "Positive Werte",
                  "type": "object",
                  "Q:options": {
                    "availabilityChecks": [
                      {
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "option-availability/barColorPositive",
                          "fields": [
                            "options",
                            "data"
                          ]
                        }
                      }
                    ]
                  },
                  "properties": {
                    "className": {
                      "title": "CSS-Klassenname",
                      "default": "",
                      "type": "string",
                      "Q:options": {
                        "placeholder": "s-viz-color-one-5"
                      }
                    },
                    "colorCode": {
                      "title": "Farbcode",
                      "type": "string",
                      "default": "",
                      "Q:type": "color"
                    }
                  }
                },
                "negative": {
                  "title": "Negative Werte",
                  "type": "object",
                  "Q:options": {
                    "availabilityChecks": [
                      {
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "option-availability/barColorNegative",
                          "fields": [
                            "options",
                            "data"
                          ]
                        }
                      }
                    ]
                  },
                  "properties": {
                    "className": {
                      "title": "CSS-Klassenname",
                      "default": "",
                      "type": "string",
                      "Q:options": {
                        "placeholder": "s-viz-color-two-3"
                      }
                    },
                    "colorCode": {
                      "title": "Farbcode",
                      "type": "string",
                      "default": "",
                      "Q:type": "color"
                    }
                  }
                }
              }
            }
          }
        },
        "heatmap": {
          "title": "Heatmap",
          "type": "object",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/heatmap",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          },
          "properties": {
            "selectedColumn": {
              "title": "Spalte auswählen",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/selectedColumn",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/selectedColumnHeatmap",
                    "fields": [
                      "options",
                      "data"
                    ]
                  }
                }
              }
            },
            "noValuesInCell": {
              "title": "Beschriftung der Werte in der Zelle entfernen",
              "type": "boolean",
              "default": false
            },
            "bucketType": {
              "title": "Bucketing Methode",
              "type": "string",
              "default": "ckmeans",
              "enum": [
                "ckmeans",
                "quantile",
                "equal",
                "custom"
              ],
              "Q:options": {
                "enum_titles": [
                  "Jenks Natural Breaks",
                  "Quantile",
                  "gleich grosse Intervalle",
                  "manuelle Grenzen"
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/numberBucketsOutOfColorScale",
                      "fields": [
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "customBuckets": {
              "title": "Manuelle Bucketgrenzen",
              "type": "string",
              "Q:options": {
                "placeholder": "z.B. 5, 15, 20, 30",
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/customBuckets",
                      "fields": [
                        "options.numericalOptions.bucketType"
                      ]
                    }
                  }
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/customBuckets",
                      "fields": [
                        "data",
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "numberBuckets": {
              "title": "Anzahl Buckets",
              "type": "number",
              "default": 5,
              "minimum": 2,
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/numberBuckets",
                      "fields": [
                        "options.numericalOptions.bucketType"
                      ]
                    }
                  }
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/numberBucketsExceedsDataSet",
                      "fields": [
                        "data",
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "scale": {
              "title": "Skala",
              "type": "string",
              "Q:options": {
                "selectType": "select",
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/scale",
                    "fields": [
                      "options.numericalOptions"
                    ]
                  }
                }
              },
              "default": "sequential"
            },
            "colorScheme": {
              "title": "Farbschema",
              "type": "string",
              "default": "one",
              "Q:options": {
                "selectType": "select",
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/colorScheme",
                    "fields": [
                      "options.numericalOptions.scale"
                    ]
                  }
                }
              }
            },
            "colorOverwrites": {
              "type": "array",
              "title": "Bucketfarbe",
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "UserHasRole",
                    "config": {
                      "role": "expert-choropleth"
                    }
                  },
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/customColors",
                      "fields": [
                        "options.numericalOptions.scale"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/colorOverwrites",
                    "fields": [
                      "options.choroplethType",
                      "options.numericalOptions"
                    ]
                  }
                },
                "layout": "compact",
                "expandable": {
                  "itemLabelTemplate": "${color} - ${position}"
                },
                "sortable": false
              },
              "items": {
                "type": "object",
                "properties": {
                  "color": {
                    "title": "Farbe",
                    "type": "string",
                    "Q:type": "color"
                  },
                  "textColor": {
                    "title": "Textfarbe",
                    "type": "string",
                    "default": "light",
                    "enum": [
                      "light",
                      "dark"
                    ],
                    "Q:options": {
                      "selectType": "select",
                      "enum_titles": [
                        "hell",
                        "dunkel"
                      ]
                    }
                  },
                  "position": {
                    "title": "Position",
                    "oneOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "Q:options": {
                      "dynamicSchema": {
                        "selectType": "select",
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "dynamic-schema/colorOverwritesItem",
                          "fields": [
                            "options.choroplethType",
                            "options.numericalOptions"
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "title",
    "data"
  ]
}

=== nzzdev/Q-table/resources/fixtures/data/heatmap-categorical.json
{
    "title": "FIXTURE: Heatmap categorical",
    "data": {
        "table": [
            [
                "Kanton",
                "Wert",
                "Wert"
            ],
            [
                "Aargau",
                "etwas",
                "etwas"
            ],
            [
                "Appenzell Ausserrhoden",
                "etwas",
                "etwas"
            ],
            [
                "Appenzell Innerrhoden",
                "etwas",
                "etwas"
            ],
            [
                "Basel-Landschaft",
                "etwas anderes",
                "etwas anderes"
            ],
            [
                "Basel-Stadt",
                "etwas",
                "etwas"
            ],
            [
                "Bern",
                "etwas",
                "etwas"
            ],
            [
                "Freiburg",
                "etwas ganz anderes",
                "etwas ganz anderes"
            ],
            [
                "Genf",
                "etwas anderes",
                "etwas anderes"
            ],
            [
                "Glarus",
                "etwas",
                "etwas"
            ],
            [
                "Graubünden",
                "etwas",
                "etwas"
            ],
            [
                "Jura",
                "etwas",
                "etwas"
            ],
            [
                "Luzern",
                "etwas anderes",
                "etwas anderes"
            ],
            [
                "Neuenburg",
                "etwas anderes",
                "etwas anderes"
            ],
            [
                "Nidwalden",
                "etwas",
                "etwas"
            ],
            [
                "Obwalden",
                "etwas",
                "etwas"
            ],
            [
                "Schaffhausen",
                "etwas",
                "etwas"
            ],
            [
                "Schwyz",
                "etwas",
                "etwas"
            ],
            [
                "Solothurn",
                "etwas ganz anderes",
                "etwas ganz anderes"
            ],
            [
                "St. Gallen",
                "etwas ganz anderes",
                "etwas ganz anderes"
            ],
            [
                "Tessin",
                "etwas",
                "etwas"
            ],
            [
                "Thurgau",
                "etwas",
                "etwas"
            ],
            [
                "Uri",
                "etwas",
                "etwas"
            ],
            [
                "Waadt",
                "etwas",
                "etwas"
            ],
            [
                "Wallis",
                "etwas",
                "etwas"
            ],
            [
                "Zug",
                "etwas",
                "etwas"
            ],
            [
                "Zürich",
                "etwas ganz anderes",
                "etwas ganz anderes"
            ]
        ],
        "metaData": {
            "cells": []
        }
    },
    "sources": [],
    "options": {
        "hideTableHeader": false,
        "showTableSearch": true,
        "cardLayout": false,
        "cardLayoutIfSmall": false,
        "minibar": {
            "invertColors": false,
            "barColor": {
                "positive": {
                    "className": "",
                    "colorCode": ""
                },
                "negative": {
                    "className": "",
                    "colorCode": ""
                }
            },
            "selectedColumn": null
        },
        "heatmap": {
            "noValuesInCell": false,
            "heatmapType": "categorical",
            "numericalOptions": {
                "bucketType": "ckmeans",
                "numberBuckets": 5,
                "scale": "sequential",
                "colorScheme": "one",
                "colorOverwrites": []
            },
            "categoricalOptions": {
                "colorOverwrites": [
                    {
                        "textColor": "light",
                        "color": "darkgrey",
                        "position": 1
                    },
                    {
                        "textColor": "dark",
                        "color": "lightgrey",
                        "position": 2
                    },
                    {
                        "textColor": "dark",
                        "color": "grey",
                        "position": 3
                    }
                ],
                "customCategoriesOrder": [
                    {
                        "category": "etwas ganz anderes"
                    }
                ]
            },
            "selectedColumn": 1
        }
    }
}

=== nzzdev/Q-table/resources/fixtures/data/one-column.json
{
  "title": "FIXTURE: simple one-column short table with numeric values",
  "subtitle": "some subtitle here",
  "data": {
    "table": [
      [
        "Punkte"
      ],
      [
        "10000000"
      ],
      [
        "20000000"
      ],
      [
        "355547.5"
      ],
      [
        "-3500000"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "options": {
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    }
  },
  "notes": "Anmerkungen",
  "sources": [
    {
      "link": {},
      "text": "Bloomberg"
    }
  ]
}

=== nzzdev/Q-table/resources/fixtures/data/special-characters.json
{
  "data": {
    "table": [
      [null, "Resultat", "xGoals", null],
      ["Russland - Saudiarabien", "5:0", "1,8 : 0,2", null],
      ["Südkorea - Deutschland", "2:0", "1,3 : 2,7", "↻"],
      ["England - Panama", "6:1", "2,8 : 1,1", null],
      ["Australien - Peru", "0:2", "1,0 : 0,2", "↻"],
      ["Island - Kroatien", "1:2", "2,2 : 0,7", "↻"],
      ["Nigeria - Island", "2:0", "0,9 : 1,3", "↻"],
      ["Russland - Ägypten", "3:1", "1,2 : 1,4", "↻"]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "hideTableHeader": false,
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    }
  },
  "title": "FIXTURE: special characters",
  "notes": "↻ = Das Spiel wäre anders ausgegangen, wenn beide Teams gleich viel aus ihren Chancen gemacht hätten.",
  "subtitle": "Spiele mit der grössten Abweichung zwischen erwartetem und effektivem Resultat"
}

=== nzzdev/Q-table/resources/fixtures/data/colorColumn-numerical-no-label.json
{
  "title": "FIXTURE: color column numeric no legend label",
  "data": {
    "table": [
      [
        "String",
        "Number",
        "Number",
        "String"
      ],
      [
        "Test1",
        "1",
        "2.1",
        "Test2"
      ],
      [
        "Test2",
        "2",
        "2.2",
        "Test2"
      ],
      [
        "Test3",
        "3",
        "2.3",
        "Test1"
      ],
      [
        "Test4",
        "4",
        "2.41",
        "Test1"
      ],
      [
        "Test5",
        "5",
        "2.5",
        "Test2"
      ],
      [
        "Test6",
        "6",
        "2.61",
        "Test1"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "hideTableHeader": false,
    "showTableSearch": false,
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    },
    "colorColumn": {
      "colorColumnType": "numerical",
      "numericalOptions": {
        "labelLegend": "noLabel",
        "bucketType": "ckmeans",
        "numberBuckets": 5,
        "scale": "sequential",
        "colorScheme": "one",
        "colorOverwrites": []
      },
      "categoricalOptions": {
        "colorOverwrites": [],
        "customCategoriesOrder": []
      },
      "selectedColumn": 2
    }
  }
}

=== nzzdev/Q-table/resources/fixtures/data/colorColumn-categorical-custom-colors.json
{
  "title": "FIXTURE: color column categorical custom colors",
  "data": {
    "table": [
      [
        "String",
        "Number",
        "Number",
        "String"
      ],
      [
        "Test1",
        "1",
        "2.1",
        "Test2"
      ],
      [
        "Test2",
        "2",
        "2.2",
        "Test2"
      ],
      [
        "Test3",
        "3",
        "2.3",
        "Test1"
      ],
      [
        "Test4",
        "4",
        "2.41",
        "Test1"
      ],
      [
        "Test5",
        "5",
        "2.5",
        "Test2"
      ],
      [
        "Test6",
        "6",
        "2.61",
        "Test1"
      ]
    ],
    "metaData": {
      "cells": [
        {
          "data": {
            "footnote": "fussnote"
          },
          "rowIndex": 4,
          "colIndex": 3
        }
      ]
    }
  },
  "sources": [],
  "options": {
    "hideTableHeader": false,
    "showTableSearch": false,
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    },
    "colorColumn": {
      "colorColumnType": "categorical",
      "numericalOptions": {
        "labelLegend": "noLabel",
        "bucketType": "ckmeans",
        "numberBuckets": 5,
        "scale": "sequential",
        "colorScheme": "one",
        "colorOverwrites": [
          {
            "textColor": "dark",
            "color": "yellow",
            "position": 1
          }
        ]
      },
      "categoricalOptions": {
        "colorOverwrites": [
          {
            "textColor": "dark",
            "color": "pink",
            "position": 1
          },
          {
            "textColor": "dark",
            "color": "lightblue",
            "position": 2
          }
        ],
        "customCategoriesOrder": []
      },
      "selectedColumn": 3
    }
  }
}
