=== nzzdev/Q-table/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Tabelle",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string",
      "Q:options": {
        "placeholder": "Der Titel bringt die Kernaussage der Tabelle auf den Punkt&#46;"
      }
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string"
    },
    "data": {
      "title": "Daten",
      "type": "object",
      "Q:type": "table",
      "Q:options": {
        "allowTranspose": false,
        "metaDataEditor": {
          "dataPropertyName": "table",
          "features": {
            "cells": {
              "propertyPath": "metaData.cells"
            }
          }
        }
      },
      "properties": {
        "table": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            }
          },
          "minItems": 1
        },
        "metaData": {
          "type": "object",
          "Q:options": {
            "compact": true
          },
          "properties": {
            "cells": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "rowIndex": {
                    "type": "number",
                    "Q:options": {
                      "hideInEditor": true
                    }
                  },
                  "colIndex": {
                    "type": "number",
                    "Q:options": {
                      "hideInEditor": true
                    }
                  },
                  "data": {
                    "type": "object",
                    "properties": {
                      "footnote": {
                        "title": "Fussnote",
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "sources": {
      "title": "Quelle(n)",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Quelle",
        "properties": {
          "text": {
            "title": "Quelle",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "Q:options": {
              "placeholder": "Direktlink zur Quelle, http://..."
            },
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }
            }
          }
        },
        "required": [
          "text"
        ]
      }
    },
    "notes": {
      "title": "Anmerkungen",
      "type": "string"
    },
    "options": {
      "title": "Optionen",
      "type": "object",
      "properties": {
        "hideTableHeader": {
          "title": "Spaltenüberschriften ausblenden",
          "type": "boolean",
          "default": false
        },
        "showTableSearch": {
          "title": "Tabellensuche anzeigen",
          "type": "boolean",
          "default": false,
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/showTableSearch",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          }
        },
        "cardLayout": {
          "title": "Card-Layout",
          "type": "boolean",
          "default": false
        },
        "cardLayoutIfSmall": {
          "title": "Card-Layout für Mobile",
          "type": "boolean",
          "default": false,
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/cardLayoutIfSmall",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          }
        },
        "minibar": {
          "title": "Minibars",
          "type": "object",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/minibars",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          },
          "properties": {
            "selectedColumn": {
              "title": "Spalte auswählen",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/selectedColumn",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/selectedColumnMinibar",
                    "fields": [
                      "options",
                      "data"
                    ]
                  }
                }
              }
            },
            "invertColors": {
              "title": "Farben invertieren",
              "type": "boolean",
              "default": false,
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/invertColors",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ]
              }
            },
            "barColor": {
              "title": "Farben manuell festlegen",
              "type": "object",
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "UserHasRole",
                    "config": {
                      "role": "expert-table"
                    }
                  },
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/barColor",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ]
              },
              "properties": {
                "positive": {
                  "title": "Positive Werte",
                  "type": "object",
                  "Q:options": {
                    "availabilityChecks": [
                      {
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "option-availability/barColorPositive",
                          "fields": [
                            "options",
                            "data"
                          ]
                        }
                      }
                    ]
                  },
                  "properties": {
                    "className": {
                      "title": "CSS-Klassenname",
                      "default": "",
                      "type": "string",
                      "Q:options": {
                        "placeholder": "s-viz-color-one-5"
                      }
                    },
                    "colorCode": {
                      "title": "Farbcode",
                      "type": "string",
                      "default": "",
                      "Q:type": "color"
                    }
                  }
                },
                "negative": {
                  "title": "Negative Werte",
                  "type": "object",
                  "Q:options": {
                    "availabilityChecks": [
                      {
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "option-availability/barColorNegative",
                          "fields": [
                            "options",
                            "data"
                          ]
                        }
                      }
                    ]
                  },
                  "properties": {
                    "className": {
                      "title": "CSS-Klassenname",
                      "default": "",
                      "type": "string",
                      "Q:options": {
                        "placeholder": "s-viz-color-two-3"
                      }
                    },
                    "colorCode": {
                      "title": "Farbcode",
                      "type": "string",
                      "default": "",
                      "Q:type": "color"
                    }
                  }
                }
              }
            }
          }
        },
        "heatmap": {
          "title": "Heatmap",
          "type": "object",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/heatmap",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          },
          "properties": {
            "selectedColumn": {
              "title": "Spalte auswählen",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/selectedColumn",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/selectedColumnHeatmap",
                    "fields": [
                      "options",
                      "data"
                    ]
                  }
                }
              }
            },
            "noValuesInCell": {
              "title": "Beschriftung der Werte in der Zelle entfernen",
              "type": "boolean",
              "default": false
            },
            "bucketType": {
              "title": "Bucketing Methode",
              "type": "string",
              "default": "ckmeans",
              "enum": [
                "ckmeans",
                "quantile",
                "equal",
                "custom"
              ],
              "Q:options": {
                "enum_titles": [
                  "Jenks Natural Breaks",
                  "Quantile",
                  "gleich grosse Intervalle",
                  "manuelle Grenzen"
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/numberBucketsOutOfColorScale",
                      "fields": [
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "customBuckets": {
              "title": "Manuelle Bucketgrenzen",
              "type": "string",
              "Q:options": {
                "placeholder": "z.B. 5, 15, 20, 30",
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/customBuckets",
                      "fields": [
                        "options.numericalOptions.bucketType"
                      ]
                    }
                  }
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/customBuckets",
                      "fields": [
                        "data",
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "numberBuckets": {
              "title": "Anzahl Buckets",
              "type": "number",
              "default": 5,
              "minimum": 2,
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/numberBuckets",
                      "fields": [
                        "options.numericalOptions.bucketType"
                      ]
                    }
                  }
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/numberBucketsExceedsDataSet",
                      "fields": [
                        "data",
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "scale": {
              "title": "Skala",
              "type": "string",
              "Q:options": {
                "selectType": "select",
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/scale",
                    "fields": [
                      "options.numericalOptions"
                    ]
                  }
                }
              },
              "default": "sequential"
            },
            "colorScheme": {
              "title": "Farbschema",
              "type": "string",
              "default": "one",
              "Q:options": {
                "selectType": "select",
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/colorScheme",
                    "fields": [
                      "options.numericalOptions.scale"
                    ]
                  }
                }
              }
            },
            "colorOverwrites": {
              "type": "array",
              "title": "Bucketfarbe",
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "UserHasRole",
                    "config": {
                      "role": "expert-choropleth"
                    }
                  },
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/customColors",
                      "fields": [
                        "options.numericalOptions.scale"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/colorOverwrites",
                    "fields": [
                      "options.choroplethType",
                      "options.numericalOptions"
                    ]
                  }
                },
                "layout": "compact",
                "expandable": {
                  "itemLabelTemplate": "${color} - ${position}"
                },
                "sortable": false
              },
              "items": {
                "type": "object",
                "properties": {
                  "color": {
                    "title": "Farbe",
                    "type": "string",
                    "Q:type": "color"
                  },
                  "textColor": {
                    "title": "Textfarbe",
                    "type": "string",
                    "default": "light",
                    "enum": [
                      "light",
                      "dark"
                    ],
                    "Q:options": {
                      "selectType": "select",
                      "enum_titles": [
                        "hell",
                        "dunkel"
                      ]
                    }
                  },
                  "position": {
                    "title": "Position",
                    "oneOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "Q:options": {
                      "dynamicSchema": {
                        "selectType": "select",
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "dynamic-schema/colorOverwritesItem",
                          "fields": [
                            "options.choroplethType",
                            "options.numericalOptions"
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "title",
    "data"
  ]
}

=== nzzdev/Q-table/resources/fixtures/data/cardlayout-mobile.json
{
  "title": "FIXTURE: cardlayout on mobile",
  "subtitle": "Subtitle",
  "data": {
    "table": [
      [
        "Kennzahlen",
        "2016",
        "2017",
        "+/-"
      ],
      [
        "Umsatz",
        "66.2",
        "70.4",
        "6"
      ],
      [
        "Betriebsergebnis Ebit",
        "7.9",
        "",
        "-19"
      ],
      [
        "Ebit-Marge (%)",
        "11.9",
        "9.1",
        null
      ],
      [
        "Konzernergebnis",
        "6.30",
        "4.10",
        "-35"
      ],
      [
        "Cashflow aus Geschäftstätigkeit",
        "8",
        "5.80",
        "-28"
      ],
      [
        "Eigenkapitalquote (%)",
        "72.3",
        "71.8",
        null
      ],
      [
        "Nettoliquidität",
        "42.30",
        "41.80",
        "-1"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "cardLayout": false,
    "cardLayoutIfSmall": true
  }
}

=== nzzdev/Q-table/resources/fixtures/data/multiline-text.json
{
  "title": "FIXTURE: multiline text",
  "subtitle": "",
  "data": {
    "table": [
      [
        "",
        "GFK",
        "Subsidiär"
      ],
      [
        "Zahl 2017",
        "119560",
        "98156"
      ],
      [
        "Definition",
        "Verfolgt aufgrund von Rasse, Nationalität, politischer Überzeugung, Religion, sexueller Orientierung",
        "Tod, Folter oder massive Gewalt drohen bei Rückkehr. Status ist aber nicht an Verfolung geknüpft"
      ],
      [
        "Regelung Familiennachzug",
        "Unbeschränkt über Visa möglich",
        "Künftig sollen 100 Angehörige pro Monat nachziehen dürfen. Härtefälle sind von dieser Regelung ausgenommen."
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "hideTableHeader": false,
    "cardLayout": false,
    "cardLayoutIfSmall": true,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    }
  }
}
