=== nzzdev/Q-table/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "title": "Tabelle",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string",
      "Q:options": {
        "placeholder": "Der Titel bringt die Kernaussage der Tabelle auf den Punkt&#46;"
      }
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string"
    },
    "data": {
      "title": "Daten",
      "type": "object",
      "Q:type": "table",
      "Q:options": {
        "allowTranspose": false,
        "metaDataEditor": {
          "dataPropertyName": "table",
          "features": {
            "cells": {
              "propertyPath": "metaData.cells"
            }
          }
        }
      },
      "properties": {
        "table": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ]
            }
          },
          "minItems": 1
        },
        "metaData": {
          "type": "object",
          "Q:options": {
            "compact": true
          },
          "properties": {
            "cells": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "rowIndex": {
                    "type": "number",
                    "Q:options": {
                      "hideInEditor": true
                    }
                  },
                  "colIndex": {
                    "type": "number",
                    "Q:options": {
                      "hideInEditor": true
                    }
                  },
                  "data": {
                    "type": "object",
                    "properties": {
                      "footnote": {
                        "title": "Fussnote",
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "sources": {
      "title": "Quelle(n)",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Quelle",
        "properties": {
          "text": {
            "title": "Quelle",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "Q:options": {
              "placeholder": "Direktlink zur Quelle, http://..."
            },
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }
            }
          }
        },
        "required": [
          "text"
        ]
      }
    },
    "notes": {
      "title": "Anmerkungen",
      "type": "string"
    },
    "options": {
      "title": "Optionen",
      "type": "object",
      "properties": {
        "hideTableHeader": {
          "title": "Spaltenüberschriften ausblenden",
          "type": "boolean",
          "default": false
        },
        "showTableSearch": {
          "title": "Tabellensuche anzeigen",
          "type": "boolean",
          "default": false,
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/showTableSearch",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          }
        },
        "cardLayout": {
          "title": "Card-Layout",
          "type": "boolean",
          "default": false
        },
        "cardLayoutIfSmall": {
          "title": "Card-Layout für Mobile",
          "type": "boolean",
          "default": false,
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/cardLayoutIfSmall",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          }
        },
        "minibar": {
          "title": "Minibars",
          "type": "object",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/minibars",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          },
          "properties": {
            "selectedColumn": {
              "title": "Spalte auswählen",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/selectedColumn",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/selectedColumnMinibar",
                    "fields": [
                      "options",
                      "data"
                    ]
                  }
                }
              }
            },
            "invertColors": {
              "title": "Farben invertieren",
              "type": "boolean",
              "default": false,
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/invertColors",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ]
              }
            },
            "barColor": {
              "title": "Farben manuell festlegen",
              "type": "object",
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "UserHasRole",
                    "config": {
                      "role": "expert-table"
                    }
                  },
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/barColor",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ]
              },
              "properties": {
                "positive": {
                  "title": "Positive Werte",
                  "type": "object",
                  "Q:options": {
                    "availabilityChecks": [
                      {
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "option-availability/barColorPositive",
                          "fields": [
                            "options",
                            "data"
                          ]
                        }
                      }
                    ]
                  },
                  "properties": {
                    "className": {
                      "title": "CSS-Klassenname",
                      "default": "",
                      "type": "string",
                      "Q:options": {
                        "placeholder": "s-viz-color-one-5"
                      }
                    },
                    "colorCode": {
                      "title": "Farbcode",
                      "type": "string",
                      "default": "",
                      "Q:type": "color"
                    }
                  }
                },
                "negative": {
                  "title": "Negative Werte",
                  "type": "object",
                  "Q:options": {
                    "availabilityChecks": [
                      {
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "option-availability/barColorNegative",
                          "fields": [
                            "options",
                            "data"
                          ]
                        }
                      }
                    ]
                  },
                  "properties": {
                    "className": {
                      "title": "CSS-Klassenname",
                      "default": "",
                      "type": "string",
                      "Q:options": {
                        "placeholder": "s-viz-color-two-3"
                      }
                    },
                    "colorCode": {
                      "title": "Farbcode",
                      "type": "string",
                      "default": "",
                      "Q:type": "color"
                    }
                  }
                }
              }
            }
          }
        },
        "heatmap": {
          "title": "Heatmap",
          "type": "object",
          "Q:options": {
            "availabilityChecks": [
              {
                "type": "ToolEndpoint",
                "config": {
                  "endpoint": "option-availability/heatmap",
                  "fields": [
                    "options",
                    "data"
                  ]
                }
              }
            ]
          },
          "properties": {
            "selectedColumn": {
              "title": "Spalte auswählen",
              "oneOf": [
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ],
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/selectedColumn",
                      "fields": [
                        "options",
                        "data"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/selectedColumnHeatmap",
                    "fields": [
                      "options",
                      "data"
                    ]
                  }
                }
              }
            },
            "noValuesInCell": {
              "title": "Beschriftung der Werte in der Zelle entfernen",
              "type": "boolean",
              "default": false
            },
            "bucketType": {
              "title": "Bucketing Methode",
              "type": "string",
              "default": "ckmeans",
              "enum": [
                "ckmeans",
                "quantile",
                "equal",
                "custom"
              ],
              "Q:options": {
                "enum_titles": [
                  "Jenks Natural Breaks",
                  "Quantile",
                  "gleich grosse Intervalle",
                  "manuelle Grenzen"
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/numberBucketsOutOfColorScale",
                      "fields": [
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "customBuckets": {
              "title": "Manuelle Bucketgrenzen",
              "type": "string",
              "Q:options": {
                "placeholder": "z.B. 5, 15, 20, 30",
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/customBuckets",
                      "fields": [
                        "options.numericalOptions.bucketType"
                      ]
                    }
                  }
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/customBuckets",
                      "fields": [
                        "data",
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "numberBuckets": {
              "title": "Anzahl Buckets",
              "type": "number",
              "default": 5,
              "minimum": 2,
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/numberBuckets",
                      "fields": [
                        "options.numericalOptions.bucketType"
                      ]
                    }
                  }
                ],
                "notificationChecks": [
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "notification/numberBucketsExceedsDataSet",
                      "fields": [
                        "data",
                        "options"
                      ]
                    },
                    "priority": {
                      "type": "medium",
                      "value": 2
                    }
                  }
                ]
              }
            },
            "scale": {
              "title": "Skala",
              "type": "string",
              "Q:options": {
                "selectType": "select",
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/scale",
                    "fields": [
                      "options.numericalOptions"
                    ]
                  }
                }
              },
              "default": "sequential"
            },
            "colorScheme": {
              "title": "Farbschema",
              "type": "string",
              "default": "one",
              "Q:options": {
                "selectType": "select",
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/colorScheme",
                    "fields": [
                      "options.numericalOptions.scale"
                    ]
                  }
                }
              }
            },
            "colorOverwrites": {
              "type": "array",
              "title": "Bucketfarbe",
              "Q:options": {
                "availabilityChecks": [
                  {
                    "type": "UserHasRole",
                    "config": {
                      "role": "expert-choropleth"
                    }
                  },
                  {
                    "type": "ToolEndpoint",
                    "config": {
                      "endpoint": "option-availability/customColors",
                      "fields": [
                        "options.numericalOptions.scale"
                      ]
                    }
                  }
                ],
                "dynamicSchema": {
                  "type": "ToolEndpoint",
                  "config": {
                    "endpoint": "dynamic-schema/colorOverwrites",
                    "fields": [
                      "options.choroplethType",
                      "options.numericalOptions"
                    ]
                  }
                },
                "layout": "compact",
                "expandable": {
                  "itemLabelTemplate": "${color} - ${position}"
                },
                "sortable": false
              },
              "items": {
                "type": "object",
                "properties": {
                  "color": {
                    "title": "Farbe",
                    "type": "string",
                    "Q:type": "color"
                  },
                  "textColor": {
                    "title": "Textfarbe",
                    "type": "string",
                    "default": "light",
                    "enum": [
                      "light",
                      "dark"
                    ],
                    "Q:options": {
                      "selectType": "select",
                      "enum_titles": [
                        "hell",
                        "dunkel"
                      ]
                    }
                  },
                  "position": {
                    "title": "Position",
                    "oneOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "Q:options": {
                      "dynamicSchema": {
                        "selectType": "select",
                        "type": "ToolEndpoint",
                        "config": {
                          "endpoint": "dynamic-schema/colorOverwritesItem",
                          "fields": [
                            "options.choroplethType",
                            "options.numericalOptions"
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "title",
    "data"
  ]
}

=== nzzdev/Q-table/resources/fixtures/data/formatted-numbers.json
{
  "title": "FIXTURE: four column numeric card layout for small",
  "subtitle": "Subtitle",
  "data": {
    "table": [
      [
        "Kennzahlen",
        "2016",
        "2017"
      ],
      [
        "Umsatz",
        "12000",
        "10000"
      ],
      [
        "Betriebsergebnis Ebit",
        "79123",
        "12333"
      ],
      [
        "Ebit-Marge (%)",
        "12332",
        "32147"
      ],
      [
        "Konzernergebnis",
        "12331",
        "10000"
      ],
      [
        "Cashflow aus Geschäftstätigkeit",
        "99999",
        "12312"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "cardLayout": false,
    "cardLayoutIfSmall": true,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    }
  }
}

=== nzzdev/Q-table/resources/fixtures/data/dates-in-data.json
{
  "title": "FIXTURE: dates in data",
  "data": {
    "table": [
      [
        "Datum",
        "Ort",
        "Magnitude",
        "Schaden"
      ],
      [
        "18.10.1356",
        "Basel",
        "6.6",
        "zerst√∂rend"
      ],
      [
        "03.09.1295",
        "Churwalden",
        "6.2",
        "schwer"
      ],
      [
        "25.07.1855",
        "Stalden-Visp",
        "6.2",
        "schwer"
      ],
      [
        "11.03.1584",
        "Aigle",
        "5.9",
        "schwer"
      ],
      [
        "18.09.1601",
        "Unterwalden",
        "5.9",
        "schwer"
      ],
      [
        "04.1524",
        "Ardon",
        "5.8",
        "schwer"
      ],
      [
        "25.01.1946",
        "Siders",
        "5.8",
        "schwer"
      ],
      [
        "09.12.1755",
        "Brig-Naters",
        "5.7",
        "schwer"
      ],
      [
        "10.09.1774",
        "Altdorf",
        "5.7",
        "mittel"
      ],
      [
        "29.04.1905",
        "Lac d'Emosson",
        "5.5",
        "mittel"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [
    {
      "link": {
        "url": "http://www.seismo.ethz.ch/de/earthquakes/switzerland/all-earthquakes/",
        "isValid": true
      },
      "text": "Schweizerischer Erdbebendienst"
    }
  ],
  "options": {
    "hideTableHeader": false,
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    }
  }
}

=== nzzdev/Q-table/resources/fixtures/data/heatmap-numerical.json
{
    "title": "FIXTURE: Heatmap numerical",
    "data": {
        "table": [
            [
                "ID",
                "Wert",
                "Wert2"
            ],
            [
                "Aargau",
                "1",
                "1"
            ],
            [
                "Appenzell Ausserrhoden",
                "2",
                "2"
            ],
            [
                "Appenzell Innerrhoden",
                "3",
                "3"
            ],
            [
                "Basel-Landschaft",
                "4",
                "4"
            ],
            [
                "Basel-Stadt",
                "5",
                "5"
            ],
            [
                "Bern",
                "6",
                "6"
            ],
            [
                "Freiburg",
                "7",
                "7"
            ],
            [
                "Genf",
                "8",
                "8"
            ],
            [
                "Glarus",
                "9",
                "9"
            ],
            [
                "Graubünden",
                "10",
                null
            ],
            [
                "Jura",
                "11",
                "11"
            ],
            [
                "Luzern",
                "12",
                "12"
            ],
            [
                "Neuenburg",
                "13",
                "13"
            ],
            [
                "Nidwalden",
                "14",
                "14"
            ],
            [
                "Obwalden",
                "15",
                "15"
            ],
            [
                "Schaffhausen",
                "16",
                "16"
            ],
            [
                "Schwyz",
                "17",
                "17"
            ],
            [
                "Solothurn",
                "18",
                "18"
            ],
            [
                "St. Gallen",
                "19",
                "19"
            ],
            [
                "Tessin",
                "20",
                "20"
            ],
            [
                "Thurgau",
                "21",
                "21"
            ],
            [
                "Uri",
                "22",
                "22"
            ],
            [
                "Waadt",
                "23",
                "23"
            ],
            [
                "Wallis",
                "24",
                "24"
            ],
            [
                "Zug",
                "25",
                "25"
            ],
            [
                "Zürich",
                "26",
                "26"
            ]
        ],
        "metaData": {
            "cells": [
                {
                    "data": {},
                    "rowIndex": 4,
                    "colIndex": 1
                }
            ]
        }
    },
    "sources": [],
    "options": {
        "hideTableHeader": false,
        "showTableSearch": false,
        "cardLayout": false,
        "cardLayoutIfSmall": false,
        "minibar": {
            "invertColors": false,
            "barColor": {
                "positive": {
                    "className": "",
                    "colorCode": ""
                },
                "negative": {
                    "className": "",
                    "colorCode": ""
                }
            },
            "selectedColumn": null
        },
        "heatmap": {
            "heatmapType": "numerical",
            "numericalOptions": {
                "bucketType": "ckmeans",
                "numberBuckets": 7,
                "scale": "sequential",
                "colorScheme": "three",
                "colorOverwrites": []
            },
            "categoricalOptions": {
                "colorOverwrites": [],
                "customCategoriesOrder": []
            },
            "selectedColumn": 2
        }
    }
}

=== nzzdev/Q-table/resources/fixtures/data/formatted-numbers-mixed.json
{
  "title": "FIXTURE: four column numeric card layout for small mixed",
  "subtitle": "Subtitle",
  "data": {
    "table": [
      ["Kennzahlen", "2016", "2017"],
      ["Umsatz", "12000", "100"],
      ["Betriebsergebnis Ebit", "79123", "2000"],
      ["Ebit-Marge (%)", "12332", "300"],
      ["Konzernergebnis", "12331", "4000"],
      ["Cashflow aus Geschäftstätigkeit", "99999", "10000"]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "cardLayout": false,
    "cardLayoutIfSmall": true
  }
}

=== nzzdev/Q-table/resources/fixtures/data/formatting.json
{
  "title": "FIXTURE: four column numeric card layout for small",
  "subtitle": "Subtitle",
  "data": {
    "table": [
      [
        "a",
        "2016"
      ],
      [
        "b",
        "12000"
      ],
      [
        "c",
        "79123"
      ],
      [
        "d",
        "12332"
      ],
      [
        "e",
        "12331"
      ],
      [
        "f",
        "12331"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "cardLayout": false,
    "cardLayoutIfSmall": true,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null,
      "formatting": [
        {
          "column": 0,
          "formattingType": "0"
        },
        {
          "column": 1,
          "formattingType": "0"
        },
        {
          "column": 2,
          "formattingType": "2"
        },
        {
          "column": 3,
          "formattingType": "0"
        },
        {
          "column": 4,
          "formattingType": "0"
        },
        {
          "column": 5,
          "formattingType": "0"
        }
      ]
    }
  }
}

=== nzzdev/Q-table/resources/fixtures/data/country-emojis.json
{
  "title": "FIXTURE: country emoji",
  "data": {
    "table": [
      [
        "header"
      ],
      [
        "ch"
      ],
      [
        "abcd"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "hideTableHeader": false,
    "showTableSearch": false,
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "countryFlagColumn": {
      "selectedColumn": 0
    }
  }
}

=== nzzdev/Q-table/resources/fixtures/data/mixed-numbers-and-text-in-cell.json
{
  "title": "FIXTURE: mixed number and text in cell",
  "subtitle": "Opel Insignia Country Tourer 2.0 BiTurbo Diesel",
  "data": {
    "table": [
      [
        "Kennzahl",
        "Wert"
      ],
      [
        "Hubraum",
        "1956 ccm"
      ],
      [
        "Motorbauart",
        "4 Zyl. Reihe, 2 Turbo, Diesel"
      ],
      [
        "Antrieb/Getriebe",
        "AWD/A8"
      ],
      [
        "Leistung",
        "154/210 kW/PS"
      ]
    ],
    "metaData": {
      "cells": []
    }
  },
  "sources": [],
  "options": {
    "hideTableHeader": true,
    "cardLayout": false,
    "cardLayoutIfSmall": false,
    "minibar": {
      "invertColors": false,
      "barColor": {
        "positive": {
          "className": "",
          "colorCode": ""
        },
        "negative": {
          "className": "",
          "colorCode": ""
        }
      },
      "selectedColumn": null
    }
  }
}
